version: '3.8'

services:
  db:
    image: postgres:16
    container_name: garageerp-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: garageerp-pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db    

  webapi:
    build:
      context: ./Garage.WebApi
      dockerfile: Dockerfile
    container_name: garageerp-webapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  postgres-data:
